#ifndef PROTOCOL
#define PROTOCOL

#define SERVERPORT 8000
#define MESSAGESIZE 128
#define CLIENTID 1111

#define NONEWEVENT 0

#define TOUCHINTERACTION 10
#define TOUCHROTATION 11
#define TOUCHTRANSLATION 12
#define TOUCHSCALE 13

#define TANGIBLEINTERACTION 20
#define TANGIBLEROTATION 21
#define TANGIBLETRANSLATION 22
#define TANGIBLESCALE 23

#endif