#ifndef PROTOCOL
#define PROTOCOL



#define SERVERPORT 8500
#define MESSAGESIZE 256
#define CLIENTID 1111
#define NUMBEROFITEMSINMESSAGE 25
#define NBPARTICLES 200

#define MAPPERMAIN 1 
#define MAPPERPLANE 2

#define NONEWEVENT 0

#define MATRIXCHANGED 10
#define OBJECTINTERACTION 11
#define CLIPPINGINTERACTION 200

#define NORMALINTERACTIONMODE 1
#define CONSTRAINEDTANGIBLE 10
#define TANGIBLEFORPLANE 20
#define SEEDPLACEMENT 40

#define TANGIBLEINTERACTION 20
#define TANGIBLEROTATION 21
#define TANGIBLETRANSLATION 22
#define TANGIBLESCALE 23

#define CHANGEDATASET 30
#define BUNNYDATASET 31
#define PARTICLESDATASET 32
#define JETLINESDATASET 33

#define RESETVIEW 40

#define ENDPROGRAM -1


#endif